# Generated by Django 3.2.6 on 2021-08-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='repetition',
            field=models.CharField(choices=[('NE', 'Never'), ('ED', 'Every day'), ('MF', 'Monday to Friday'), ('EW', 'Every week (Friday)'), ('EM', 'Every month (Same date)'), ('EY', 'Every year (Same date)')], default='NE', max_length=2),
        ),
    ]
